[package]
name = "example-runtime-service"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
configlab = { path = "../.." }
serde.workspace = true
serde_json.workspace = true
