//! Typed configuration contract and generated binding metadata.

use crate::{ConfigBuilder, ConfigError, EffectiveConfiguration, Schema};
/// Contract generated by `#[derive(Config)]` for a typed configuration struct.
///
/// Application code normally starts with [`Config::builder`]. The metadata and
/// decoding methods are public so generated implementations remain ordinary
/// Rust, but they must not contain precedence or selector logic.
///
/// # Compile-time validation
///
/// Unsupported helper attributes fail at the field that contains them:
///
/// ```compile_fail
/// use configlab::Config;
///
/// #[derive(Config)]
/// struct InvalidAttribute {
///     #[config(unknown_attribute)]
///     value: u16,
/// }
/// ```
///
/// Mutually exclusive field roles are rejected before code generation:
///
/// ```compile_fail
/// use configlab::Config;
///
/// #[derive(Config)]
/// struct InvalidRole {
///     #[config(nested, value)]
///     child: String,
/// }
/// ```
///
/// Conditional requirements must target optional fields:
///
/// ```compile_fail
/// use configlab::Config;
///
/// #[derive(Config)]
/// struct InvalidRequirement {
///     enabled: bool,
///     #[config(required_when = "enabled")]
///     endpoint: String,
/// }
/// ```
pub trait Config: Sized {
    /// Builds the kernel schema for this type beneath `prefix`.
    fn schema(prefix: &str) -> Result<Schema, ConfigError>;

    /// Decodes one definition-valid effective configuration into this type.
    fn decode(effective: &EffectiveConfiguration, prefix: &str) -> Result<Self, ConfigError>;

    /// Runs typed validators after kernel resolution and decoding.
    fn validate(&self) -> Vec<ValidationIssue> {
        Vec::new()
    }

    /// Returns environment bindings generated for the type.
    fn env_bindings(prefix: &str) -> Vec<EnvBinding> {
        let _ = prefix;
        Vec::new()
    }

    /// Returns direct CLI flag bindings generated for the type.
    fn cli_bindings(prefix: &str) -> Vec<CliBinding> {
        let _ = prefix;
        Vec::new()
    }

    /// Returns internal paths representing optional nested section presence.
    #[doc(hidden)]
    fn optional_groups(prefix: &str) -> Vec<String> {
        let _ = prefix;
        Vec::new()
    }

    /// Starts an ergonomic local configuration load.
    fn builder() -> ConfigBuilder<Self> {
        ConfigBuilder::new()
    }
}

/// Severity for typed, application-provided validators.
///
/// Kernel definition diagnostics use [`crate::DiagnosticSeverity`]; this type exists
/// for post-decode validators that operate on the concrete Rust struct.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Severity {
    /// Blocks successful typed application validation.
    Error,
    /// Preserves the typed configuration while surfacing an application concern.
    Warning,
}

/// One issue returned by a typed field/struct/builder validator.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidationIssue {
    /// Blocking versus non-blocking severity.
    pub severity: Severity,
    /// Optional typed configuration path associated with the issue.
    pub path: Option<String>,
    /// Human-readable message. Callers must not include secret material.
    pub message: String,
}

impl ValidationIssue {
    /// Creates a pathless blocking validation issue.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Error,
            path: None,
            message: message.into(),
        }
    }

    /// Creates a path-associated blocking validation issue.
    pub fn at(path: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Error,
            path: Some(path.into()),
            message: message.into(),
        }
    }

    /// Creates a pathless non-blocking validation issue.
    pub fn warning(message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Warning,
            path: None,
            message: message.into(),
        }
    }

    /// Creates a path-associated non-blocking validation issue.
    pub fn warning_at(path: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Warning,
            path: Some(path.into()),
            message: message.into(),
        }
    }

    /// Prefixes the issue path while leaving pathless messages associated with the prefix.
    #[must_use]
    pub fn prefixed(mut self, prefix: &str) -> Self {
        if !prefix.is_empty() {
            self.path = Some(match self.path.take() {
                Some(path) => format!("{prefix}.{path}"),
                None => prefix.into(),
            });
        }
        self
    }
}

/// Generated environment-variable naming strategy.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EnvName {
    /// Exact name unaffected by a builder-level prefix.
    Exact(String),
    /// Name segments that receive nested/root prefixes before joining.
    Auto(Vec<String>),
    /// Environment loading is disabled for this field.
    Disabled,
}

/// Maps one effective path to an environment-variable naming rule.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EnvBinding {
    /// Effective kernel setting path.
    pub path: String,
    /// Environment naming rule for that path.
    pub name: EnvName,
}

/// Maps one effective path to an application-specific command-line flag.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CliBinding {
    /// Effective kernel setting path.
    pub path: String,
    /// Command-line flag name without leading dashes.
    pub flag: String,
    /// Whether the field supports `--flag` / `--no-flag` boolean shorthand.
    pub boolean: bool,
}
